server:
  port: 8006
spring:
  application:
    name: cloud-consul-payment
  cloud:
    consul:
      host: 106.15.60.91
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true