server:
  port: 80
spring:
  application:
    name: cloud-consul-order
  cloud:
    consul:
      host: 106.15.60.91
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true